/* 
	Copyright(C) 2018 The University of Texas at Dallas
	Developed By: Muhammet Emin Yanik
	Advisor: Prof. Murat Torlak
	Department of Electrical and Computer Engineering

	This work was supported by the Semiconductor Research Corporation (SRC) task 2712.029
	through The University of Texas at Dallas' Texas Analog Center of Excellence (TxACE).

	Redistributions and use of source must retain the above copyright notice
	Redistributions in binary form must reproduce the above copyright notice
*/

/*
  Module Name:

	main.c

  Abstract:

	The entry point of the application
*/

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include <RadarTrigger.h>


/*
	This code counts pulses generated by the Motion Controller
	and triggers Radar after a predefined number of pulses

	Functionality of GPIOs used in this example:
     GPIO4 - pulse input pin,
     GPIO5 - control input pin.
    
	To do this test, you should connect the pulse output of the Motion Controller to GPIO4.
	GPIO5 is the control signal, you can leave it floating with internal pull up,
	or connect it to ground. If left floating, the count value will be increasing.
	If you connect GPIO5 to GND, the count value will be decreasing.
  
	The radar is triggered when the counter value:
	reaches a threshold value,
*/


TaskHandle_t xRadarTriggerTask;  // A task handle for the radar trigger

void app_main(void)
{	
    // /* Create the task, storing the handle. */
    BaseType_t xReturned;

    xReturned = xTaskCreatePinnedToCore(
                        vRadarTriggerTask,      /* Function that implements the task. */
                    	"RadarTriggerTask",     /* Text name for the task. */
                    	2048,                   /* Stack size in words, not bytes. */
                    	NULL,               	/* Parameter passed into the task. */
                    	5,                      /* Priority at which the task is created. */
                    	&xRadarTriggerTask,     /* Used to pass out the created task's handle. */
                        0);	                    /* Core number. */

    if( xReturned != pdPASS )
    {
        /* The task is not created. */
        printf("The Radar Trigger Task could not created.");
    }
	
}